
version: "3.3"
services:
  node:
    image: delicious:0.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7777:7777"
    env_file: 
      - variables.env
    volumes: 
      - ./app:/delicious/app
    networks:
      - network
    depends_on:
      - mongo
  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
      - "27017:27017"
      networks:
      - network
      expose:
        - '27017'
networks:
  network:
    driver: bridge
